# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 20:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0002_auto_20171020_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteevent',
            old_name='notification_time',
            new_name='notification_sent_time',
        ),
        migrations.AlterField(
            model_name='drevent',
            name='last_status_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 20, 16, 15, 91415, tzinfo=utc), verbose_name='Last Status Time'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='last_opt_in',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 20, 16, 15, 92325, tzinfo=utc), verbose_name='Last opt-in'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='last_status_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 20, 20, 16, 15, 92281, tzinfo=utc), verbose_name='Last Status Time'),
        ),
    ]
