# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 17:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0005_auto_20171020_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='ven_id',
            field=models.CharField(default='919a1dfa088fe14b79f9', max_length=100, unique=True, verbose_name='VEN ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='ven_name',
            field=models.CharField(default='ven2', max_length=100, unique=True, verbose_name='VEN Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='utility_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Utility ID'),
        ),
        migrations.AlterField(
            model_name='drevent',
            name='last_status_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 2, 17, 28, 46, 85319), null=True, verbose_name='Last Status Time'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='last_opt_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 2, 17, 28, 46, 86122), null=True, verbose_name='Last opt-in'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='last_status_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 2, 17, 28, 46, 86079), verbose_name='Last Status Time'),
        ),
    ]
