# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 16:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0007_auto_20171102_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='drevent',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vtn.DREvent'),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vtn.SiteEvent'),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='superseded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='drevent',
            name='last_status_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 7, 16, 48, 23, 588930), null=True, verbose_name='Last Status Time'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='last_opt_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 7, 16, 48, 23, 589848), null=True, verbose_name='Last opt-in'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='last_status_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 16, 48, 23, 589806), verbose_name='Last Status Time'),
        ),
    ]
