# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 21:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0008_auto_20171107_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteevent',
            name='modification_number',
            field=models.IntegerField(default=0, verbose_name='Modification Number'),
        ),
        migrations.AlterField(
            model_name='drevent',
            name='last_status_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 7, 21, 12, 8, 844799), null=True, verbose_name='Last Status Time'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='last_opt_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 7, 21, 12, 8, 845723), null=True, verbose_name='Last opt-in'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='last_status_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 21, 12, 8, 845664), verbose_name='Last Status Time'),
        ),
    ]
