# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 16:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0010_auto_20171108_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drevent',
            name='last_status_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 8, 16, 17, 59, 660463), null=True, verbose_name='Last Status Time'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='last_opt_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 8, 16, 17, 59, 661607), null=True, verbose_name='Last opt-in'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='last_status_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 16, 17, 59, 661526), verbose_name='Last Status Time'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='opt_in',
            field=models.CharField(choices=[('optIn', 'Opted-in'), ('optOut', 'Not opted-in'), ('none', 'Neither')], default='none', max_length=100),
        ),
    ]
