# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 17:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0011_auto_20171108_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='drevent',
            name='version_number',
            field=models.IntegerField(blank=True, default=1, verbose_name='Version'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drevent',
            name='last_status_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 8, 17, 11, 13, 783331), null=True, verbose_name='Last Status Time'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='last_opt_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 8, 17, 11, 13, 784929), null=True, verbose_name='Last opt-in'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='last_status_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 17, 11, 13, 784830), verbose_name='Last Status Time'),
        ),
    ]
