# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 17:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0012_auto_20171108_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drevent',
            name='last_status_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 8, 17, 12, 21, 678069), null=True, verbose_name='Last Status Time'),
        ),
        migrations.AlterField(
            model_name='drevent',
            name='version_number',
            field=models.IntegerField(blank=True, default=1, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='last_opt_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 8, 17, 12, 21, 679075), null=True, verbose_name='Last opt-in'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='last_status_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 17, 12, 21, 679012), verbose_name='Last Status Time'),
        ),
    ]
