# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 19:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0013_auto_20171108_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteevent',
            name='superseded',
        ),
        migrations.AddField(
            model_name='drevent',
            name='superseded',
            field=models.BooleanField(default=False, verbose_name='Superseded'),
        ),
        migrations.AlterField(
            model_name='drevent',
            name='last_status_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 8, 19, 51, 33, 861469), null=True, verbose_name='Last Status Time'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='last_opt_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 8, 19, 51, 33, 862496), null=True, verbose_name='Last opt-in'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='last_status_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 19, 51, 33, 862432), verbose_name='Last Status Time'),
        ),
    ]
