# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 20:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0014_auto_20171108_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteevent',
            name='superseded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='drevent',
            name='last_status_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 8, 20, 38, 32, 842079), null=True, verbose_name='Last Status Time'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='last_opt_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 8, 20, 38, 32, 843086), null=True, verbose_name='Last opt-in'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='last_status_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 8, 20, 38, 32, 843022), verbose_name='Last Status Time'),
        ),
    ]
