# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 21:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0016_auto_20171109_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteevent',
            name='ven_status',
            field=models.CharField(choices=[('not_told', 'not_told'), ('told', 'told'), ('acknowledged', 'acknowledged')], default='not_told', max_length=100),
        ),
        migrations.AlterField(
            model_name='drevent',
            name='last_status_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 9, 21, 6, 52, 994840), null=True, verbose_name='Last Status Time'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='last_opt_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 9, 21, 6, 52, 995925), null=True, verbose_name='Last opt-in'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='last_status_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 9, 21, 6, 52, 995839), verbose_name='Last Status Time'),
        ),
    ]
