# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 22:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0017_auto_20171109_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drevent',
            name='version_number',
        ),
        migrations.AlterField(
            model_name='drevent',
            name='last_status_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 9, 22, 6, 42, 914511), null=True, verbose_name='Last Status Time'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='last_opt_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 9, 22, 6, 42, 915525), null=True, verbose_name='Last opt-in'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='last_status_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 9, 22, 6, 42, 915439), verbose_name='Last Status Time'),
        ),
    ]
