# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 19:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0019_auto_20171109_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drevent',
            name='last_status_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 13, 19, 8, 51, 606210), null=True, verbose_name='Last Status Time'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='last_opt_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 13, 19, 8, 51, 607232), null=True, verbose_name='Last opt-in'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='last_status_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 13, 19, 8, 51, 607146), verbose_name='Last Status Time'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'SCHEDULED'), ('NOTIFICATION_SENT', 'NOTIFICATION'), ('ACTIVE', 'ACTIVE'), ('COMPLETED', 'COMPLETED'), ('REPORTED', 'REPORTED'), ('CANCELED', 'CANCELED'), ('DELETED', 'DELETED'), ('ERROR', 'ERROR')], default='SCHEDULED', max_length=100),
        ),
    ]
