# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 18:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0022_auto_20171114_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_specifier_id', models.CharField(blank=True, max_length=100, null=True)),
                ('report_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('start', models.CharField(blank=True, max_length=100, null=True)),
                ('end', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(choices=[('scheduled', 'scheduled'), ('active', 'active'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='scheduled', max_length=100)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vtn.Site')),
            ],
        ),
        migrations.RemoveField(
            model_name='reports',
            name='site',
        ),
        migrations.AlterField(
            model_name='drevent',
            name='last_status_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 14, 18, 1, 14, 433165), null=True, verbose_name='Last Status Time'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='last_opt_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 14, 18, 1, 14, 435059), null=True, verbose_name='Last opt-in'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='last_status_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 14, 18, 1, 14, 434927), verbose_name='Last Status Time'),
        ),
        migrations.DeleteModel(
            name='Reports',
        ),
        migrations.AddField(
            model_name='report',
            name='site_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vtn.SiteEvent'),
        ),
    ]
