# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 19:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0024_auto_20171114_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='state',
            new_name='status',
        ),
        migrations.AddField(
            model_name='report',
            name='ven_status',
            field=models.CharField(choices=[('not_told', 'not_told'), ('told', 'told'), ('acknowledged', 'acknowledged')], default='not_told', max_length=100),
        ),
        migrations.AlterField(
            model_name='drevent',
            name='last_status_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 14, 19, 25, 30, 24101), null=True, verbose_name='Last Status Time'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='last_opt_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 14, 19, 25, 30, 25157), null=True, verbose_name='Last opt-in'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='last_status_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 14, 19, 25, 30, 25069), verbose_name='Last Status Time'),
        ),
    ]
