# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 17:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0027_auto_20171115_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='ven_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='VEN ID'),
        ),
        migrations.AlterField(
            model_name='drevent',
            name='last_status_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 15, 17, 33, 6, 546501), null=True, verbose_name='Last Status Time'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='last_opt_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 15, 17, 33, 6, 547648), null=True, verbose_name='Last opt-in'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='last_status_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 15, 17, 33, 6, 547555), verbose_name='Last Status Time'),
        ),
    ]
