# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 21:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0029_auto_20171115_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drevent',
            options={'verbose_name_plural': 'DR Events'},
        ),
        migrations.AlterModelOptions(
            name='drprogram',
            options={'verbose_name_plural': 'DR Programs'},
        ),
        migrations.AlterModelOptions(
            name='siteevent',
            options={'verbose_name_plural': 'Site Events'},
        ),
        migrations.AlterModelOptions(
            name='supportedreports',
            options={'verbose_name_plural': 'Supported Reports'},
        ),
        migrations.AlterField(
            model_name='drevent',
            name='last_status_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 15, 21, 25, 22, 122409), null=True, verbose_name='Last Status Time'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='last_opt_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 15, 21, 25, 22, 124220), null=True, verbose_name='Last opt-in'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='last_status_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 15, 21, 25, 22, 124081), verbose_name='Last Status Time'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='opt_in',
            field=models.CharField(choices=[('optIn', 'optIn'), ('optOut', 'optOut'), ('none', 'Neither')], default='none', max_length=100),
        ),
    ]
