# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0031_auto_20171115_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drevent',
            name='status',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('far', 'far'), ('near', 'near'), ('active', 'active'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('unresponded', 'unresponded')], default='far', max_length=100, verbose_name='Event Status'),
        ),
    ]
