# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0033_auto_20171116_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='end',
        ),
        migrations.RemoveField(
            model_name='report',
            name='start',
        ),
    ]
