# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 15:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0035_auto_20171116_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='site',
        ),
        migrations.RemoveField(
            model_name='report',
            name='site_event',
        ),
        migrations.AlterField(
            model_name='drevent',
            name='scheduled_notification_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 15, 45, 40, 261036), verbose_name='Scheduled Notification Time'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
