# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0039_auto_20171120_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='site',
        ),
    ]
