# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0040_remove_report_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='site',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='vtn.Site'),
            preserve_default=False,
        ),
    ]
