# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0041_report_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportedreports',
            name='site',
        ),
        migrations.RemoveField(
            model_name='report',
            name='site',
        ),
        migrations.DeleteModel(
            name='SupportedReports',
        ),
    ]
