# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0042_auto_20171120_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drevent',
            options={'verbose_name': 'DR Event', 'verbose_name_plural': 'DR Events'},
        ),
    ]
