# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0043_auto_20171121_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_address1',
            field=models.CharField(max_length=100, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_address2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 2'),
        ),
    ]
