# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0045_site_last_status_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='reporting_status',
        ),
    ]
