# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0046_remove_site_reporting_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drprogram',
            options={'verbose_name': 'DR Program', 'verbose_name_plural': 'DR Programs'},
        ),
        migrations.AlterModelOptions(
            name='telemetry',
            options={'verbose_name_plural': 'Telemetry'},
        ),
    ]
