# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0049_drevent_request_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drevent',
            name='request_id',
        ),
        migrations.AddField(
            model_name='siteevent',
            name='request_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Request ID'),
        ),
    ]
