# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0050_auto_20171128_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteevent',
            name='request_id',
        ),
    ]
