# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0051_remove_siteevent_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteevent',
            name='status',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('far', 'far'), ('near', 'near'), ('active', 'active'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('unresponded', 'unresponded')], default='scheduled', max_length=100),
        ),
    ]
