# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0052_auto_20171201_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drevent',
            name='previous_version',
        ),
        migrations.RemoveField(
            model_name='siteevent',
            name='superseded',
        ),
    ]
