# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0056_auto_20171206_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_status',
            field=models.CharField(choices=[('active', 'active'), ('cancelled', 'cancelled'), ('cancelled_by_user', 'cancelled_by_user')], default='active', max_length=100),
        ),
    ]
