# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0057_report_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ven_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='VEN ID'),
        ),
    ]
