# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtn', '0058_report_ven_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_request_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Report Request ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_status',
            field=models.CharField(choices=[('active', 'active'), ('cancelled', 'cancelled'), ('cancelled_requested', 'cancelled_requested')], default='active', max_length=100, verbose_name='Report Status'),
        ),
        migrations.AlterField(
            model_name='site',
            name='ip_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='IP address'),
        ),
    ]
